version: "3.7"

services:
  client:
    build:
      context: ./client
      args: 
        CLIENT_BACKEND_URL: $CLIENT_BACKEND_URL
    environment:
      - CLIENT_BACKEND_URL=http://localhost:5000/api
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    ports:
      - "3000:80"
  server:
    build:
      context: ./server
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
    ports: 
      - "5000:5000"
